export const INC_VARIABLE = 'INC_VARIABLE';
export const DEC_VARIABLE = 'DEC_VARIABLE';
export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_APPLICATION_LANGUAGE = 'SET_APPLICATION_LANGUAGE';
