export const SET_SEARCH_VALUE = 'SET_SEARCH_VALUE';
export const SET_APPLICATION_LANGUAGE = 'SET_APPLICATION_LANGUAGE';
export const SET_COUNTRY_CONFIG = 'SET_COUNTRY_CONFIG';
export const SET_CURRENT_PERSON = 'SET_CURRENT_PERSON';
export const SET_PLACES_BY_COUNTRY = 'SET_PLACES_BY_COUNTRY';
export const SET_PREV_STATE = 'SET_PREV_STATE';
export const SET_IS_AUTHORIZED = 'SET_IS_AUTHORIZED';
