export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_APPLICATION_LANGUAGE = "SET_APPLICATION_LANGUAGE";
export const SET_COUNTRY_CONFIG = "SET_COUNTRY_CONFIG";
export const SET_IS_AUTHORIZED = "SET_IS_AUTHORIZED";
